[tools]
ast-grep = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
lua = "5.1"
node = "latest"
tree-sitter = "latest"
uv = "latest"
watchexec = "latest"
yq = "latest"
zellij = "latest"
