[tools]
ast-grep = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
lua = "5.1"
neovim = "latest"
node = "latest"
python = "latest"
rg = "latest"
tree-sitter = "latest"
uv = "latest"
watchexec = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
